### ISSUE TITLE
The app gives me a white screen after giving team URL

### ISSUE THREAD

**Issue by toogy** [mattermost/ios#19]
When I launch the app I get the screen that asks for the team URL.

Once I submit that form I get a white screen and nothing else :disappointed: 

Am I missing something?

I use the last version on an iPhone 5C

**Comment by lfbrock** [comment]
Hi @toogy, I think this is fixed now - if you were using mattermost/platform:latest or mattermost/platform:dev there was a bug on master, but it's now been fixed.

**Comment by toogy** [comment]
Oh actually, updating my iPhone to the last iOS version fixed it

**Comment by ipsecguy** [comment]
Did not fix for me. Android Apps work, iPhone and iPad have the white screen after giving team URL. Using Docker, may it is fixed in a later version?

Mattermost Team Edition T0 Version: 2.1.0 Build Number: 6562 Build Date: Thu Mar 17 16:17:34 UTC 2016 Build Hash: 2cd006474ec8a808b2ea2b0502a842f44cb0b127

**Comment by lfbrock** [comment]
Hi @ipsecguy, I think the build you are on might be the issue. The official v2.1 build was Mar 14, people who got the Mar 17 build seem to be hitting this issue.

**Comment by chiel1980** [comment]
I know this is an old issue but I got the same behaviour using the latest mattermost from git (pulled 24 november 2016) and using iOS 10.1.1. 
Mattermost with Nginx proxy and docker containers, version info:
```
Mattermost Enterprise Edition

Modern communication from behind your firewall.

Version: 3.4.0
Database: postgres
Learn more about Enterprise Edition at about.mattermost.com
Copyright 2016 Mattermost, Inc. All rights reserved
Build Hash: 57f25fa59c71821cc38fd220b133aa6a40815e12
EE Build Hash: 36fc7e2f85dfd758264e54080261d2b5c8ef573a
Build Date: Wed Sep 14 13:04:40 UTC 2016
```

It did connect the first time, but after a while it just turned into the white screen.
Restart of iOS, reinstall of the app did not work. I can enter my servername but after that I get the enable/disable notification question from iOS and I receive a white screen.
